# <span>Worksheet - 0</span>
## <span>Review on Python Programming and Numpy for Deep Learning</span>
<small>

**Student Name:** Pratisha Bista  
**ID:** 2408284  
**Group:** L6CG1  

</small>

# 4. TO - DO - Task [PYTHON]

## 4.1. Exercises on Functions:
*Task-1*

In [3]:
print("Categories:")
print("l : Length (m, ft)")
print("w : Weight (kg, lbs)")
print("v : Volume (L, gal)\n")

cat = input("Choose category (l/w/v): ")

if cat == "l":
    print("Available units: m (meters), ft (feet)")
elif cat == "w":
    print("Available units: kg (kilograms), lbs (pounds)")
elif cat == "v":
    print("Available units: L (liters), gal (gallons)")
else:
    print("Invalid category")
    exit()

unit1 = input("Convert from: ")
unit2 = input("Convert to: ")

try:
    num1 = float(input("Enter value: "))
except ValueError:
    print("Invalid number entered")
    exit()

def convert(unit1, unit2, num1):
    """
    Converts the entered value from one unit to another.

    Parameters:
    unit1 (str): the unit to convert from
    unit2 (str): the unit to convert to
    num1 (float): the value to be converted

    Returns:
    float or str: converted value if valid otherwise throws error message
    """

    # length
    if unit1 == "m" and unit2 == "ft":
        return num1 * 3.28084
    elif unit1 == "ft" and unit2 == "m":
        return num1 / 3.28084

    # weight
    elif unit1 == "kg" and unit2 == "lbs":
        return num1 * 2.204623
    elif unit1 == "lbs" and unit2 == "kg":
        return num1 / 2.204623

    # volume
    elif unit1 == "L" and unit2 == "gal":
        return num1 * 0.2641720524
    elif unit1 == "gal" and unit2 == "L":
        return num1 / 0.2641720524

    else:
        return "Invalid conversion"

ans = convert(unit1, unit2, num1)

print(num1, unit1, "in", unit2, "is", ans)

Categories:
l : Length (m, ft)
w : Weight (kg, lbs)
v : Volume (L, gal)

Available units: kg (kilograms), lbs (pounds)
55.0 kg in lbs is 121.25426500000002


*Task-2*

In [2]:
operations = {
    "1": "Sum",
    "2": "Average",
    "3": "Maximum",
    "4": "Minimum"
}

print("Available operations:")
for key, name in operations.items():
    print(f"{key}: {name}")
print()

while True:
    cat = input("Choose operation (1/2/3/4): ")

    if cat not in operations:
        print("Invalid operation choice. Please enter 1, 2, 3, or 4.\n")
        continue  

    nums = input("Enter numbers separated by spaces: ")

    try:
        num_list = [float(n) for n in nums.split()]
        if len(num_list) == 0:
            print("List is empty. Try again.\n")
            continue  
    except ValueError:
        print("Invalid input: enter only numbers.\n")
        continue  

    break


def operate(cat, num_list):
    """
    Performs a mathematical operation on a list of numbers.

    Parameters:
    cat (str): operation type ("1"=sum, "2"=average, "3"=max, "4"=min)
    num_list (list): list of numeric values

    Returns:
    float: result of operation
    """

    if cat == "1":  # sum
        total = 0
        for n in num_list:
            total += n
        return total

    elif cat == "2":  # average
        total = 0
        for n in num_list:
            total += n
        return total / len(num_list)

    elif cat == "3":  # maximum
        maximum = num_list[0]
        for n in num_list:
            if n > maximum:
                maximum = n
        return maximum

    elif cat == "4":  # minimum
        minimum = num_list[0]
        for n in num_list:
            if n < minimum:
                minimum = n
        return minimum


ans = operate(cat, num_list)

print(f"\nThe {operations[cat]} of the numbers {num_list} is {ans}")

Available operations:
1: Sum
2: Average
3: Maximum
4: Minimum

Invalid operation choice. Please enter 1, 2, 3, or 4.


The Sum of the numbers [2.0, 6.0, 8.0, 9.0, 9.0] is 34.0


## 4.2. Exercise on List Manipulation

1. Extract every other element

In [11]:
num_list = [int(n) for n in input("Enter numbers separated by spaces: ").split()]

def extract_every_other(lst):
    """
    Returns a new list containing every other element from the input list, 
    starting from the first element.

    Parameters:
    lst (list): the original list

    Returns:
    list: new list with every other element
    """
    ans = []
    for i in range(0, len(num_list), 2):  # range(start, stop, step)
        ans.append(lst[i])
    return ans

new_list = extract_every_other(num_list)

print("Original list:", num_list)
print("Every other element:", new_list)
    

Original list: [3, 4, 8, 6, 7]
Every other element: [3, 8, 7]


2. Slice a sublist

In [10]:
num_list = [int(n) for n in input("Enter numbers separated by spaces: ").split()]

start = int(input("Enter starting index: "))
end = int(input("Enter ending index: "))

def get_sublist(lst, start, end):
    """Returns a sublist from start to end (inclusive)."""
    return lst[start:end+1]

sublist = get_sublist(num_list, start, end)

print("Original list:", num_list)
print(f"Sublist from index {start} to {end}:", sublist)

Original list: [2, 4, 5, 6, 7, 8]
Sublist from index 1 to 4: [4, 5, 6, 7]


3. Reverse a List Using Slicing

In [9]:
num_list = [int(n) for n in input("Enter numbers separated by spaces: ").split()]

def reverse_list(lst):
    """
    Returns a reversed version of the input list using slicing.

    Parameters:
    lst (list): The original list

    Returns:
    list: Reversed list
    """
    return lst[::-1]

reversed_lst = reverse_list(num_list)

print("Original list:", num_list)
print("Reversed list:", reversed_lst)

Original list: [2, 3, 5, 7, 8]
Reversed list: [8, 7, 5, 3, 2]


4. Remove the first and last elements

In [12]:
num_list = [int(n) for n in input("Enter numbers separated by spaces: ").split()]

def remove_first_last(lst):
    """
    Returns a sublist of the input list with the first and last elements removed.

    Parameters:
    lst (list): original list

    Returns:
    list: list without the first and last elements
    """
    return lst[1:-1]

new_list = remove_first_last(num_list)

print("Original list:", num_list)
print("After removing first and last elements:", new_list)

Original list: [1, 2, 9, 1, 8]
After removing first and last elements: [2, 9, 1]


5. Get the first n elements

In [19]:
num_list = [int(n) for n in input("Enter numbers separated by spaces: ").split()]

n = int(input("Enter how many elements to get: "))

def get_first_n(lst, n):
    """
    Returns the first n elements from the input list.

    Parameters:
    lst (list): the original list
    n (int): number of elements to extract from the start

    Returns:
    list: list containing the first n elements
    """
    return lst[:n]

print("Original list:", num_list)
print(f"First {n} elements:", get_first_n(num_list, n))

Original list: [1, 4, 6, 7]
First 2 elements: [1, 4]


6. Extract elements from the end

In [18]:
num_list = [int(n) for n in input("Enter numbers separated by spaces: ").split()]
n = int(input("Enter how many elements to get: "))

def get_last_n(lst, n):
    """
    Returns the last n elements from the input list.

    Parameters:
    lst (list): original list
    n (int): number of elements to extract from the end

    Returns:
    list: list containing the last n elements
    """
    return lst[-n:]

print("Original list:", num_list)
print(f"Last {n} elements:", get_last_n(num_list, n))

Original list: [1, 4, 6, 7]
Last 2 elements: [6, 7]


7. Extract elements in reverse order

In [17]:
num_list = [int(n) for n in input("Enter numbers separated by spaces: ").split()]
def reverse_skip(lst):
    """
    Returns a list of every second element starting from the second-to-last element, moving backward.

    Parameters:
    lst (list): original list

    Returns:
    list: new list with elements in reverse, skipping one each time
    """
    return lst[-2::-2]

print("Original list:", num_list)
print(f"Revered elements containing every second element starting from the second-to-last:\n", reverse_skip(num_list))

Original list: [1, 2, 4, 7, 8, 9]
Revered elements containing every second element starting from the second-to-last:
 [8, 4, 1]


## 4.3. Exercise on nested list

1. Flatten a nested list

In [20]:
def flatten(lst):
    """
    Flattens a nested list into a single list.

    Parameters:
    lst (list): nested list (list of lists)

    Returns:
    list: flattened list with all elements in a single dimension
    """
    result = []
    for sublist in lst:        
        for item in sublist:   
            result.append(item)
    return result

nested_list = [[1, 2], [3, 4], [5]]
flat_list = flatten(nested_list)

print("Original nested list:", nested_list)
print("Flattened list:", flat_list)

Original nested list: [[1, 2], [3, 4], [5]]
Flattened list: [1, 2, 3, 4, 5]


2. Accessing nested list elements

In [22]:
def access_nested_element(lst, indices):
    """
    Returns the element from a nested list using a list of indices.

    Parameters:
    lst (list): nested list
    indices (list): list of indices to navigate the nested list

    Returns:
    element: the element at the specified nested position
    """
    result = lst
    for index in indices:
        result = result[index]  
    return result

nested_list = [[1, 2, 3], [4, 5, 6], [7, 8, 9]]
indices = [1, 0]  

element = access_nested_element(nested_list, indices)

print("Nested list:", nested_list)
print(f"Element at indices {indices}:", element)

Nested list: [[1, 2, 3], [4, 5, 6], [7, 8, 9]]
Element at indices [1, 0]: 4


3. Sum of All Elements in a Nested List

In [23]:
def sum_nested(lst):
    """
    Recursively calculates the sum of all numbers in a nested list.

    Parameters:
    lst (list): nested list of numbers (can contain sublists)

    Returns:
    int/float: sum of all numbers in the nested list
    """
    total = 0
    for item in lst:
        if isinstance(item, list):      
            total += sum_nested(item)
        else:                            
            total += item
    return total

nested_list = [[1, 2], [3, [4, 5]], 6]
result = sum_nested(nested_list)

print("Nested list:", nested_list)
print("Sum of all elements:", result)

Nested list: [[1, 2], [3, [4, 5]], 6]
Sum of all elements: 21


4. Remove Specific Element from a Nested List

In [24]:
def remove_element(lst, elem):
    """
    Removes all occurrences of a specific element from a nested list.

    Parameters:
    lst (list): nested list (list of lists)
    elem: element to remove

    Returns:
    list: nested list with the element removed from all sublists
    """
    result = []
    for sublist in lst:
        new_sublist = [x for x in sublist if x != elem]
        result.append(new_sublist)
    return result

nested_list = [[1, 2], [3, 2], [4, 5]]
element_to_remove = 2

modified_list = remove_element(nested_list, element_to_remove)

print("Original nested list:", nested_list)
print(f"Nested list after removing {element_to_remove}:", modified_list)

Original nested list: [[1, 2], [3, 2], [4, 5]]
Nested list after removing 2: [[1], [3], [4, 5]]


5. Find the Maximum Element in a Nested List

In [25]:
def find_max(lst):
    """
    Finds the maximum element in a nested list (any depth).

    Parameters:
    lst (list): nested list

    Returns:
    int/float: maximum element
    """
    maximum = float('-inf')
    for item in lst:
        if isinstance(item, list):
            maximum = max(maximum, find_max(item))
        else:
            maximum = max(maximum, item)
    return maximum

nested_list = [[1, 2], [3, [4, 5]], 6]
print("Maximum:", find_max(nested_list))

Maximum: 6


6. Count Occurrences of an Element in a Nested List

In [26]:
def count_occurrences(lst, elem):
    """
    Counts how many times elem appears in a nested list.

    Parameters:
    lst (list): nested list
    elem: element to count

    Returns:
    int: number of occurrences
    """
    count = 0
    for item in lst:
        if isinstance(item, list):
            count += count_occurrences(item, elem)
        elif item == elem:
            count += 1
    return count

nested_list = [[1, 2], [2, 3], [2, 4]]
print("Occurrences of 2:", count_occurrences(nested_list, 2))

Occurrences of 2: 3


7. Flatten a List of Lists of Lists

In [27]:
def deep_flatten(lst):
    """
    Flattens a nested list of arbitrary depth into a single list.

    Parameters:
    lst (list): nested list

    Returns:
    list: flattened list
    """
    result = []
    for item in lst:
        if isinstance(item, list):
            result.extend(deep_flatten(item))
        else:
            result.append(item)
    return result

nested_list = [[[1, 2], [3, 4]], [[5, 6], [7, 8]]]
print("Deep flattened:", deep_flatten(nested_list))

Deep flattened: [1, 2, 3, 4, 5, 6, 7, 8]


8. Nested List Average

In [28]:
def average_nested(lst):
    """
    Calculates the average of all elements in a nested list.

    Parameters:
    lst (list): nested list

    Returns:
    float: average value
    """
    flat_list = deep_flatten(lst)
    return sum(flat_list) / len(flat_list) if flat_list else 0

nested_list = [[1, 2], [3, 4], [5, 6]]
print("Average:", average_nested(nested_list))

Average: 3.5


# 10. TO - DO - Task [NumPy]

## 10.1 Basic Vector and Matrix Operation with Numpy

### Problem - 1: Array Creation

In [4]:
import numpy as np

empty_arr = np.empty((2, 2))
print("1. Empty 2x2 Array:\n", empty_arr)

ones_arr = np.ones((4, 2))
print("\n2. Ones 4x2 Array:\n", ones_arr)

full_arr = np.full((3, 3), 9)
print("\n3. Full 3x3 Array (Value=9):\n", full_arr)

zeros_like_arr = np.zeros_like(full_arr)
print("\n4. Zeros like full_arr:\n", zeros_like_arr)

ones_like_arr = np.ones_like(full_arr)
print("\n5. Ones like full_arr:\n", ones_like_arr)

new_list = [1, 2, 3, 4]
np_list_arr = np.array(new_list)
print("\n6. List to Array:\n", np_list_arr)

1. Empty 2x2 Array:
 [[4.9e-324 9.9e-324]
 [1.5e-323 2.0e-323]]

2. Ones 4x2 Array:
 [[1. 1.]
 [1. 1.]
 [1. 1.]
 [1. 1.]]

3. Full 3x3 Array (Value=9):
 [[9 9 9]
 [9 9 9]
 [9 9 9]]

4. Zeros like full_arr:
 [[0 0 0]
 [0 0 0]
 [0 0 0]]

5. Ones like full_arr:
 [[1 1 1]
 [1 1 1]
 [1 1 1]]

6. List to Array:
 [1 2 3 4]


### Problem - 2: Array Manipulation: Numerical Ranges and Array indexing

In [5]:
arr_10_49 = np.arange(10, 50)
print("1. Array 10-49:\n", arr_10_49)

matrix_3x3 = np.arange(9).reshape(3, 3)
print("\n2. 3x3 Matrix 0-8:\n", matrix_3x3)

identity_3x3 = np.eye(3)
print("\n3. 3x3 Identity Matrix:\n", identity_3x3)

rand_arr_30 = np.random.random(30)
print("\n4. Mean of random array (30 elements):", rand_arr_30.mean())

rand_10x10 = np.random.random((10, 10))
print("\n5. 10x10 Random Min:", rand_10x10.min(), "Max:", rand_10x10.max())

zero_10 = np.zeros(10)
zero_10[4] = 1 
print("\n6. Array with 5th element as 1:\n", zero_10)

arr_to_rev = np.array([1, 2, 0, 0, 4, 0])
rev_arr = arr_to_rev[::-1]
print("\n7. Reversed Array:\n", rev_arr)

border_arr = np.ones((5, 5))
border_arr[1:-1, 1:-1] = 0
print("\n8. Border 2D Array:\n", border_arr)

checkerboard = np.zeros((8, 8), dtype=int)
checkerboard[1::2, ::2] = 1
checkerboard[::2, 1::2] = 1
print("\n9. 8x8 Checkerboard Pattern:\n", checkerboard)

1. Array 10-49:
 [10 11 12 13 14 15 16 17 18 19 20 21 22 23 24 25 26 27 28 29 30 31 32 33
 34 35 36 37 38 39 40 41 42 43 44 45 46 47 48 49]

2. 3x3 Matrix 0-8:
 [[0 1 2]
 [3 4 5]
 [6 7 8]]

3. 3x3 Identity Matrix:
 [[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]

4. Mean of random array (30 elements): 0.46474002097990524

5. 10x10 Random Min: 0.0026431547228892294 Max: 0.9956153599630307

6. Array with 5th element as 1:
 [0. 0. 0. 0. 1. 0. 0. 0. 0. 0.]

7. Reversed Array:
 [0 4 0 0 2 1]

8. Border 2D Array:
 [[1. 1. 1. 1. 1.]
 [1. 0. 0. 0. 1.]
 [1. 0. 0. 0. 1.]
 [1. 0. 0. 0. 1.]
 [1. 1. 1. 1. 1.]]

9. 8x8 Checkerboard Pattern:
 [[0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]]


### Problem - 3: Array Operations

In [6]:
x = np.array([[1, 2], [3, 5]])
y = np.array([[5, 6], [7, 8]])
v = np.array([9, 10])
w = np.array([11, 12])

print("1. x + y:\n", x + y)

print("\n2. x - y:\n", x - y)

print("\n3. x * 2:\n", x * 2)

print("\n4. x squared:\n", np.square(x))

print("\n5. Dot product v.w:", np.dot(v, w))
print("Dot product x.v:", np.dot(x, v))
print("Dot product x.y:\n", np.dot(x, y))

print("\n6. Concatenate x & y along rows (vstack):\n", np.vstack((x, y)))
print("Concatenate v & w along columns (column_stack):\n", np.column_stack((v, w)))

try:
    print("\n7. Trying to concatenate x and v:")
    np.concatenate((x, v))
except Exception as e:
    print("Error:", e)
    print("Explanation: x is 2D (2x2) and v is 1D (size 2). Dimensions must match for concatenation.")

1. x + y:
 [[ 6  8]
 [10 13]]

2. x - y:
 [[-4 -4]
 [-4 -3]]

3. x * 2:
 [[ 2  4]
 [ 6 10]]

4. x squared:
 [[ 1  4]
 [ 9 25]]

5. Dot product v.w: 219
Dot product x.v: [29 77]
Dot product x.y:
 [[19 22]
 [50 58]]

6. Concatenate x & y along rows (vstack):
 [[1 2]
 [3 5]
 [5 6]
 [7 8]]
Concatenate v & w along columns (column_stack):
 [[ 9 11]
 [10 12]]

7. Trying to concatenate x and v:
Error: all the input arrays must have same number of dimensions, but the array at index 0 has 2 dimension(s) and the array at index 1 has 1 dimension(s)
Explanation: x is 2D (2x2) and v is 1D (size 2). Dimensions must match for concatenation.


### Problem - 4: Matrix Operations

In [7]:
A = np.array([[3, 4], [7, 8]])
B = np.array([[5, 3], [2, 1]])

# Prove A.A^-1 = I
inv_A = np.linalg.inv(A)
print("1. A dot inv(A):\n", np.around(np.dot(A, inv_A), decimals=5))

# Prove AB != BA
AB = np.dot(A, B)
BA = np.dot(B, A)
print("\n2. AB:\n", AB)
print("BA:\n", BA)
print("AB == BA?", np.array_equal(AB, BA))

# Prove (AB)^T = B^T A^T
lhs = AB.T
rhs = np.dot(B.T, A.T)
print("\n3. (AB)^T:\n", lhs)
print("B^T dot A^T:\n", rhs)
print("Equal?", np.array_equal(lhs, rhs))

# Solve system of Linear equations:
# 2x - 3y + z = -1
# x - y + 2z = -3
# 3x + y - z = 9

coeffs = np.array([[2, -3, 1], [1, -1, 2], [3, 1, -1]])
consts = np.array([-1, -3, 9])

# Using Inverse Method: X = A^-1 B
X = np.dot(np.linalg.inv(coeffs), consts)
print("\nSolve using Inverse Method:")
print("x =", X[0], "y =", X[1], "z =", X[2])

# Solve using linalg.solve
X_solve = np.linalg.solve(coeffs, consts)
print("\nSolve using solve method:", X_solve)

1. A dot inv(A):
 [[1. 0.]
 [0. 1.]]

2. AB:
 [[23 13]
 [51 29]]
BA:
 [[36 44]
 [13 16]]
AB == BA? False

3. (AB)^T:
 [[23 51]
 [13 29]]
B^T dot A^T:
 [[23 51]
 [13 29]]
Equal? True

Solve using Inverse Method:
x = 2.0 y = 1.0 z = -2.0

Solve using solve method: [ 2.  1. -2.]


## 10.2 Experiment: How Fast is Numpy?

In [8]:
import time
size = 1_000_000

L1 = list(range(size))
L2 = list(range(size))
A1 = np.arange(size)
A2 = np.arange(size)

# Element-wise Addition
start = time.time()
res_list = [x + y for x, y in zip(L1, L2)]
print(f"Addition (Python List): {time.time() - start:.5f} sec")

start = time.time()
res_arr = A1 + A2
print(f"Addition (NumPy):       {time.time() - start:.5f} sec")

# Element-wise Multiplication
start = time.time()
res_list = [x * y for x, y in zip(L1, L2)]
print(f"\nMultiplication (Python List): {time.time() - start:.5f} sec")

start = time.time()
res_arr = A1 * A2
print(f"Multiplication (NumPy):       {time.time() - start:.5f} sec")

# Dot Product
start = time.time()
res_list = sum([x * y for x, y in zip(L1, L2)])
print(f"\nDot Product (Python List): {time.time() - start:.5f} sec")

start = time.time()
res_arr = np.dot(A1, A2)
print(f"Dot Product (NumPy):       {time.time() - start:.5f} sec")

# Matrix Multiplication (1000x1000)
M1 = np.random.random((1000, 1000))
M2 = np.random.random((1000, 1000))
M1_list = M1.tolist()
M2_list = M2.tolist()

# Python Matrix Addition (Simulating complexity)
start = time.time()
res = [[sum(a * b for a, b in zip(row_a, col_b)) 
        for col_b in zip(*M2_list)] for row_a in M1_list]
print(f"\nMatrix Mult (Python List): {time.time() - start:.5f} sec")

start = time.time()
res = np.dot(M1, M2)
print(f"Matrix Mult (NumPy):       {time.time() - start:.5f} sec")

Addition (Python List): 0.16755 sec
Addition (NumPy):       0.00899 sec

Multiplication (Python List): 0.18889 sec
Multiplication (NumPy):       0.00880 sec

Dot Product (Python List): 0.27276 sec
Dot Product (NumPy):       0.00328 sec

Matrix Mult (Python List): 184.31647 sec
Matrix Mult (NumPy):       0.05633 sec


NumPy is approximately 18 times faster when performing addition. For multiplication, it performs about 21 times faster. In the case of the dot product, NumPy is roughly 83 times faster. Finally, for matrix multiplication, Python loops take significantly more time, whereas NumPy is about 3,272 times faster.